version: 2.1
jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - test