apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodeserver-pipeline
spec:
  resources:
    - name: source-repo
      type: git
    - name: web-image
      type: image
  tasks:
    - name: build-nodeserver-image
      taskRef:
        name: build-docker-image
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
          value: /workspace/git-source/node_sample #configure: may change according to your source
      resources:
        inputs:
          - name: git-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: web-image
    - name: deploy-nodeserver
      taskRef:
        name: deploy-using-kubectl
      resources:
        inputs:
          - name: source
            resource: source-repo
          - name: image
            resource: web-image
            from:
              - build-nodeserver-image
      params:
        - name: path
          value: /workspace/source/node_sample/kubernetes/deployment.yaml #configure: may change according to your source
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"