# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
  labels:
    app: node-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
        - name: node-server-container
          image: samsonites/nodejs_ci
          ports:
            - containerPort: 8000

---
# declare service
apiVersion: v1
kind: Service
metadata:
  name: nodeserver-service
spec:
  type: NodePort
  selector:
    app: node-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000